version: '3.4'

services:
  dockerizingwebapi:
    container_name: webapibackend
    image: ebarrioscode/dockerizingwebapi
    build:
      context: .
      dockerfile: DockerizingWebApi/Dockerfile
    depends_on:
      - database

  database:
    image: microsoft/mssql-server-linux:2017-CU3
    container_name: webapidb
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "<YourStrong!Passw0rd>"